### ISSUE TITLE
Error 500 upon upgrade to latest YearBox!

### ISSUE THREAD

**Issue by gabuzom** [micgro42/yearbox#11]
Upgrade of YearBox to latest version made my whole doku install crash with mention 

PHP Parse error:  syntax error, unexpected '=' in /var/www/doku//lib/plugins/yearbox/syntax.php on line 83

Running
Release 2020-07-29 "Hogfather".
nginx version: nginx/1.14.1
PHP 7.0.33-0+deb9u10 (fpm-fcgi) (built: Oct  6 2020 17:08:28)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u10, Copyright (c) 1999-2017, by Zend Technologies

Tell me what info i can get you to help diagnose, if interested!

**Comment by micgro42** [comment]
Hey, thanks for letting me know! I think I know what the issue is, could you try to install the Plugin from the second-newest commit and see if it works: https://github.com/micgro42/yearbox/zipball/3d1075d384f31c6893bc0571f5998927f9ac3853

**Comment by gabuzom** [comment]
Indeed, it is working!! Thanks for the tip, and thanks for useful work on the nice plugin in general!

**Comment by micgro42** [comment]
Thanks for confirming! That version should be functionally identical to the current version.

The cause is that your PHP version is a bit old. PHP 7.0 stopped receiving official security updates two years ago and most modern PHP software thus stopped supporting it.

I would advise updating to PHP 7.4, which will still be supported for a while and the upgrade shouldn't make any problems with software that also runs under 7.0.

I've updated the [official Dokuwiki page of the yearbox plugin](https://www.dokuwiki.org/plugin:yearbox) to indicate that it needs PHP 7.2, and point to the link provided above for those that still are on a very outdated PHP version.
