### ISSUE TITLE
translations are stuck on translate.dokuwiki.org

### ISSUE THREAD

**Issue by schplurtz** [micgro42/yearbox#2]
Hi,

I'm not sure if I should report this here on somewhere on dokuwiki.org, but just in case...

yearbox plugin is flagged "processing" and it's not possible to add new translations.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/1008292/90976031-fd130480-e539-11ea-87c9-efd15cf33e84.png">

**Comment by Klap-in** [comment]
I guess that the import fails due to too complex format of the language file for the simple importer of the translation tool.
The translation tool does not support arrays (only for js strings).

https://github.com/micgro42/yearbox/blob/ee247dbfff24b3ac541a89dc7961e51fa3ec4b76/lang/en/lang.php#L11-L12

Proposed solution: the array has to be rewritten in 12 lines instead of an array. If keys are used with numbers (i.e. 'month1', 'month2',..), directly the relevant month can be retrieved from `getLang()`

https://github.com/micgro42/yearbox/blob/ee247dbfff24b3ac541a89dc7961e51fa3ec4b76/syntax.php#L297-L309

**Comment by micgro42** [comment]
Implemented the proposed solution. Could you check whether it works now as expected on translate.dokuwiki.org?

**Comment by Klap-in** [comment]
The plugin is now available in the translation tool: https://translate.dokuwiki.org/plugin/yearbox
Nice!

**Comment by micgro42** [comment]
Yep, it works now. Thank you all :blush:
